// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbVXVnrRfjzpy8VE_XDFvbSDgI4iSJ0F0',
    appId: '1:865941903171:web:70d63c12b473cecf72c1f6',
    messagingSenderId: '865941903171',
    projectId: 'library-booking-bb097',
    authDomain: 'library-booking-bb097.firebaseapp.com',
    storageBucket: 'library-booking-bb097.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZqaNYJGo0_nzfvjwlARB_ECd7Q8ymFZI',
    appId: '1:865941903171:android:49d144122049031972c1f6',
    messagingSenderId: '865941903171',
    projectId: 'library-booking-bb097',
    storageBucket: 'library-booking-bb097.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-vtclfIiPuhJ8CjXHQY1RYn_FzR1jiLE',
    appId: '1:865941903171:ios:98612957fb035a0e72c1f6',
    messagingSenderId: '865941903171',
    projectId: 'library-booking-bb097',
    storageBucket: 'library-booking-bb097.firebasestorage.app',
    iosBundleId: 'com.example.libraryBooking',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-vtclfIiPuhJ8CjXHQY1RYn_FzR1jiLE',
    appId: '1:865941903171:ios:98612957fb035a0e72c1f6',
    messagingSenderId: '865941903171',
    projectId: 'library-booking-bb097',
    storageBucket: 'library-booking-bb097.firebasestorage.app',
    iosBundleId: 'com.example.libraryBooking',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAbVXVnrRfjzpy8VE_XDFvbSDgI4iSJ0F0',
    appId: '1:865941903171:web:52bac45ab5df01d372c1f6',
    messagingSenderId: '865941903171',
    projectId: 'library-booking-bb097',
    authDomain: 'library-booking-bb097.firebaseapp.com',
    storageBucket: 'library-booking-bb097.firebasestorage.app',
  );

}